### ISSUE TITLE
Unable to send WhatsApp message to unsaved numbers....

### ISSUE THREAD

**Issue by NOTtheKRish** [alann-maulana/share_whatsapp#3]
Hello!... In my app, I'd like to make users send message via WhatsApp to any person... So, when I try sending message to saved contacts, no issue... But when I try to send a message to unsaved numbers... chat doesn't appear to open.. How can I overcome this issue??

**Comment by ihzadeprian1305** [comment]
Hello! Sorry for my english, this is a good plugin, when i used shareWhatsapp.share, overall i can send the files to the selected phone number, but i cannot send the text, how can i solve this?

**Comment by alann-maulana** [comment]
@NOTtheKRish the only think we can send message to unsaved number is via wa.me url

**Comment by NOTtheKRish** [comment]
@alann-maulana I actually got the solution buddy...  using **url_launcher** package
