### ISSUE TITLE
Error to share imagem

### ISSUE THREAD

**Issue by felipeparente** [alann-maulana/share_whatsapp#5]
I'm trying to share a dynamic image to a specific contact, but the lib doesn't send it.
In my case, the image is generated with canvas, and sent to the contact, but the lib shows me the list of contacts to choose one, the correct thing would be to go directly to the contact I entered.
`await ShareWhatsapp().share(type: WhatsApp.standard, phone: telefone, file: XFile(fileAux.path));`

If before trying to send the image, I send a message to the contact and then try to send an image, it works.

**Comment by alann-maulana** [comment]
Yeah that was an expected behavior

**Comment by felipeparente** [comment]
As I am specifying the contact number, in the "phone" field, shouldn't it fall directly to this contact?
